title: Hong Yi Cheng Lin
#description: I am a Mathematics and Physics (MMathPhys) student at the University of Warwick with a passion for Python programming. I taught myself the basics and then decided to deepen my knowledge through some university modules.
language: en

# Multilingual settings
languages:
  en:
    description: "I am a Mathematics and Physics (MMathPhys) student at the University of Warwick with a passion for Python programming. I taught myself the basics and then decided to deepen my knowledge through some university modules."
  es:
    description: "Descripci√≥n"

show_downloads: False
theme: jekyll-theme-minimal
